<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <AssemblyName>BXBHomework</AssemblyName>
    <RootNamespace>BxbHomework.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250205002" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\node_modules\markdown-it\dist\markdown-it.min.js" Link="MarkdownAssets\markdown-it.min.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\node_modules\markdown-it-texmath\texmath.js" Link="MarkdownAssets\texmath.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\node_modules\katex\dist\katex.min.js" Link="MarkdownAssets\katex.min.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\node_modules\katex\dist\katex.min.css" Link="MarkdownAssets\katex.min.css" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\node_modules\dompurify\dist\purify.min.js" Link="MarkdownAssets\purify.min.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\node_modules\katex\dist\fonts\**\*.*" CopyToOutputDirectory="PreserveNewest">
      <Link>MarkdownAssets\fonts\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
</Project>
